### ISSUE TITLE
Running Spectra with mouse data?

### ISSUE THREAD

**Issue by jws777** [dpeerlab/spectra#40]
Hi, really excited about this analysis approach but I am wondering how can I adapt it to mouse data please?

I understand from reading the Cytopus vignette that I should just be able to create a custom dictionary incorporating mouse genesets, but do you have any thoughts on an efficient way to do that? I.e. for the default human dictionary, did you pull the genesets from an existing database or did you have to curate them manually?

I am principally interested in running just the mouse equivalent of the global genesets since my sequencing data is from a single cell type.

Thanks so much for any thoughts or pointers for this!

**Comment by wallet-maker** [comment]
Hi,
thank you for using Spectra. Currently we don't have a knowledge base available for mouse. Please see our methods section  https://doi.org/10.1038/s41587-023-01940-3 on how we compiled the gene sets for the default knowledge base used in the paper. The idea was to offer something that goes beyond common databases which are still mainly designed for bulk RNA sequencing data. However, we also used external datasources which are partly available for mouse (see Methods). The custom gene sets we used are mainly cell type specific.

A straightforward approach you can try would be to iterate over the dictionary used as an input for Spectra and convert human to mouse genes (e.g. using bioservices package). This should work for most gene sets because Spectra is quite tolerant to genes which are not coherently expressed with the remaining genes in the gene set. 
 
I will close this issue but feel free to reopen if that does not help.

Thanks,
Thomas
